config/routes.rb
SampleApp::Application.routes.draw do

  root 'apis#index'

  resources :apis do
    collection do
      post :result
    end
  end

end

app/controllers/apis_controller.rb
class ApisController < ApplicationController

	include API

	# Root action and renders a index page which contains a form
	# to take usernames of twitter, github or rubygems
	#
	def index

	end

	# Usernames will get submitted here as POST
	# Hits api's of twitter, github and rubygems
	# If any erros between api interactions, corresponding
	# variables will be assigned with empty in rescue block
	# Renders results page and displays the data collected 
	# from apis with download option
	#
	def result
		username = params[:username]

	  begin
	  	@twitter = API::Twitter.tweets username
	  rescue Exception => e
	  	@twitter = []
	  end

	  begin
	  	@github_user = API::GitHub.user username
	  	@github_repos = API::GitHub.repos username
	  rescue Exception => e
	  	@github_user = ""
		  @github_repos = []
	  end

	  begin
	  	@gems = API::RubyGems.published username
	  rescue Exception => e
	  	@gems = []
	  end

	  render "result"
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apis/index.html.erb
<div class="full-wrapper">
    <div class="wrapper">
       <div class="inner-wrapper">
          <h2 class="h2">Hello!!!</h2>
          <h4 class="h4">Enter the username to see recent Tweets, Git contributions and published RubyGems...</h4>
          <%= form_tag result_apis_path, method: "post" do %>
            <div class="input-box">
            <%= text_field_tag :username, nil, placeholder: "Username" %>
            </div>
            <div class="button-wrapper">
              <div class="button"><%= submit_tag("Go") %>
              </div>
            </div>
          <% end %>
       </div>  
     </div>
</div>

app/views/apis/result.html.erb
<div class="full-wrapper">
    <div class="wrapper-new">
			<h1 class="h1">Listing results from Twitter, Github and RubyGems!!</h1>
			<% unless @twitter.empty? %>
			<h4>Recent tweets</h4>
			<ul class="list-group">
			  <% @twitter.each do |t|%>
			    <li class="list-group-item"><%= t.text %></li>
			  <% end %>
			</ul>
			<% end %>

			<% unless @github_repos.empty? %>
			<h4>Github repositories</h4>
			<h5> Date of Joining: <%= @github_user["created_at"].to_time.strftime("%A, %B %d %Y") %></h5>
			<ul class="list-group">
			  <% @github_repos.each do |gr|%>
			    <li class="list-group-item"><%= gr %></li>
			  <% end %>
			</ul>
			<% end %>

			<% unless @gems.empty? %>
			<h4>Published gems</h4>
			<ul class="list-group">
			  <% @gems.each do |g|%>
			    <li class="list-group-item"><%= g %></li>
			  <% end %>
			</ul>
			<% end %>

			<%= link_to 'Download', '#', :onclick => "window.print()"  %> | 
			<%= link_to 'Back', root_path  %>
	  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
   <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <%= yield %>

</body>
</html>